// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0
// source: pessoa.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pessoa struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nome string `protobuf:"bytes,1,opt,name=nome,proto3" json:"nome,omitempty"`
}

func (x *Pessoa) Reset() {
	*x = Pessoa{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pessoa_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pessoa) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pessoa) ProtoMessage() {}

func (x *Pessoa) ProtoReflect() protoreflect.Message {
	mi := &file_pessoa_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pessoa.ProtoReflect.Descriptor instead.
func (*Pessoa) Descriptor() ([]byte, []int) {
	return file_pessoa_proto_rawDescGZIP(), []int{0}
}

func (x *Pessoa) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

type PessoaResut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nome string `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
}

func (x *PessoaResut) Reset() {
	*x = PessoaResut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pessoa_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PessoaResut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PessoaResut) ProtoMessage() {}

func (x *PessoaResut) ProtoReflect() protoreflect.Message {
	mi := &file_pessoa_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PessoaResut.ProtoReflect.Descriptor instead.
func (*PessoaResut) Descriptor() ([]byte, []int) {
	return file_pessoa_proto_rawDescGZIP(), []int{1}
}

func (x *PessoaResut) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PessoaResut) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

var File_pessoa_proto protoreflect.FileDescriptor

var file_pessoa_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x65, 0x73, 0x73, 0x6f, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1c,
	0x0a, 0x06, 0x50, 0x65, 0x73, 0x73, 0x6f, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x6d, 0x65, 0x22, 0x31, 0x0a, 0x0b,
	0x50, 0x65, 0x73, 0x73, 0x6f, 0x61, 0x52, 0x65, 0x73, 0x75, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x6f, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x6d, 0x65, 0x32,
	0x38, 0x0a, 0x0d, 0x50, 0x65, 0x73, 0x73, 0x6f, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x27, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x65, 0x73, 0x73, 0x6f, 0x61,
	0x12, 0x07, 0x2e, 0x50, 0x65, 0x73, 0x73, 0x6f, 0x61, 0x1a, 0x0c, 0x2e, 0x50, 0x65, 0x73, 0x73,
	0x6f, 0x61, 0x52, 0x65, 0x73, 0x75, 0x74, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x67, 0x72, 0x70,
	0x63, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pessoa_proto_rawDescOnce sync.Once
	file_pessoa_proto_rawDescData = file_pessoa_proto_rawDesc
)

func file_pessoa_proto_rawDescGZIP() []byte {
	file_pessoa_proto_rawDescOnce.Do(func() {
		file_pessoa_proto_rawDescData = protoimpl.X.CompressGZIP(file_pessoa_proto_rawDescData)
	})
	return file_pessoa_proto_rawDescData
}

var file_pessoa_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pessoa_proto_goTypes = []any{
	(*Pessoa)(nil),      // 0: Pessoa
	(*PessoaResut)(nil), // 1: PessoaResut
}
var file_pessoa_proto_depIdxs = []int32{
	0, // 0: PessoaService.CreatePessoa:input_type -> Pessoa
	1, // 1: PessoaService.CreatePessoa:output_type -> PessoaResut
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pessoa_proto_init() }
func file_pessoa_proto_init() {
	if File_pessoa_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pessoa_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Pessoa); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pessoa_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*PessoaResut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pessoa_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pessoa_proto_goTypes,
		DependencyIndexes: file_pessoa_proto_depIdxs,
		MessageInfos:      file_pessoa_proto_msgTypes,
	}.Build()
	File_pessoa_proto = out.File
	file_pessoa_proto_rawDesc = nil
	file_pessoa_proto_goTypes = nil
	file_pessoa_proto_depIdxs = nil
}
